<?php

declare(strict_types=1);

namespace Tests\Unit\Services;


use App\Models\Show;
use App\Repository\DatabaseRepository;
use App\Repository\TVMazeRepository;
use App\Services\ShowsService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Config;
use Mockery;
use ReflectionClass;
use Tests\TestCase;

class ShowsServiceTest extends TestCase
{
    use RefreshDatabase;

    private $databaseRepository;

    private $tvMazeRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->databaseRepository = Mockery::mock(DatabaseRepository::class);
        $this->tvMazeRepository = Mockery::mock(TVMazeRepository::class);

        Config::set('shows.shows', 'shows');
        Config::set('shows.search_shows', 'search');
    }

    public function testProcessLimit(): void
    {
        $data = [
            'show_id' => 300
        ];

        $this->databaseRepository
            ->shouldReceive('fetchLatest')
            ->andReturn($data);
        $showService = new ShowsService($this->tvMazeRepository, $this->databaseRepository);
        $result = $this->invokeMethod($showService, 'processLimit', []);

        $this->assertEquals(ceil($data['show_id'] / 250), $result);
    }

    public function invokeMethod(&$object, string $methodName, array $parameters = [])
    {
        $reflection = new ReflectionClass(get_class($object));
        $method = $reflection->getMethod($methodName);
        $method->setAccessible(true);

        return $method->invokeArgs($object, $parameters);
    }

    public function testProcessShowArray(): void
    {
        $show = Show::factory()->make();

        $data = [
            [
                'id' => $show['show_id'],
                'name' => $show['name'],
                'image' => $show['image'],
                'url' => $show['link'],
                'status' => $show['status'],
            ]
        ];

        $expected = [
            'name' => $show['name'],
            'image' => $show['image'],
            'link' => $show['link'],
            'show_id' => $show['show_id'],
            'status' => $show['status'],
        ];


        $showService = new ShowsService($this->tvMazeRepository, $this->databaseRepository);

        $result = $this->invokeMethod($showService, 'processShowArray', $data);

        $this->assertEquals($result['name'], $show['name']);
    }
}
